name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  # Run cargo test --workspace
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
      - name: Cache
        uses: actions/cache@v4
        with:
          save-always: true
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-test-${{ hashFiles('**/Cargo.toml') }}
      - name: Install Nix
        uses: cachix/install-nix-action@3715ab1a11cac9e991980d7b4a28d80c7ebdd8f9 # v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@0fc020193b5a1fa3ac4575aa3a7d3aa6a35435ad # v16
        with:
          name: airac-aixm-updater
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Run cargo test
        run: nix develop --command cargo tarpaulin --verbose --all-features --workspace --timeout 120 --out xml
      - uses: k1LoW/octocov-action@v1

  # Run cargo clippy --workspace -- -D warnings
  clippy_check:
    name: Clippy
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
      - name: Cache
        uses: actions/cache@v4
        with:
          save-always: true
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-clippy-${{ hashFiles('**/Cargo.toml') }}
      - name: Install Nix
        uses: cachix/install-nix-action@3715ab1a11cac9e991980d7b4a28d80c7ebdd8f9 # v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@0fc020193b5a1fa3ac4575aa3a7d3aa6a35435ad # v16
        with:
          name: airac-aixm-updater
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Run clippy
        run: nix develop --command cargo clippy --workspace -- -D warnings

  # Run cargo fmt --all -- --check
  format:
    name: Format
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
      - name: Install Nix
        uses: cachix/install-nix-action@3715ab1a11cac9e991980d7b4a28d80c7ebdd8f9 # v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@0fc020193b5a1fa3ac4575aa3a7d3aa6a35435ad # v16
        with:
          name: airac-aixm-updater
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Run cargo fmt
        run: nix develop --command cargo fmt --all -- --check
